version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201711-01

    environment:
      - CI_SYSTEM: circleci

    steps:
      - checkout

      - run:
          name: Update dependencies
          command: |
            ./tests/update-dependencies.sh

      - run:
          name: Run tests
          command: |
            ./tests/test.sh

      - run:
          name: Move artifacts
          command: |
            mkdir artifacts
            mv node artifacts

      - store_artifacts:
          path: artifacts

  build_with_branch:
    machine:
      image: circleci/classic:201711-01

    environment:
      - CI_SYSTEM: circleci

    steps:
      - checkout

      - run:
          name: Update dependencies
          command: |
            ./tests/update-dependencies.sh $CIRCLE_BRANCH

      - run:
          name: Run tests
          command: |
            ./tests/test.sh $CIRCLE_BRANCH

      - run:
          name: Move artifacts
          command: |
            mkdir artifacts
            mv node artifacts

      - store_artifacts:
          path: artifacts

workflows:
  version: 2
  test_both_versions:
    jobs:
      # This tests both ./setup.sh and ./setup.sh <branch>
      - build
      - build_with_branch
