version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01

    environment:
      - CI_SYSTEM: circleci

    steps:
      - checkout

      - run:
          name: Update dependencies
          command: |
            ./tests/update-dependencies.sh

      - run:
          name: Run tests
          command: |
            ./tests/test.sh

      - run:
          name: Move artifacts
          command: |
            mkdir artifacts
            mv node artifacts

      - store_artifacts:
          path: artifacts

  build_with_branch:
    machine:
      image: ubuntu-2004:202104-01

    environment:
      - CI_SYSTEM: circleci

    steps:
      - checkout

      - run:
          name: Update dependencies
          command: |
            ./tests/update-dependencies.sh $CIRCLE_BRANCH

      - run:
          name: Run tests
          command: |
            ./tests/test.sh $CIRCLE_BRANCH

      - run:
          name: Move artifacts
          command: |
            mkdir artifacts
            mv node artifacts

      - store_artifacts:
          path: artifacts

  build_and_push:
    docker:
      - image: docker:20.10.6

    environment:
      - CI_SYSTEM: circleci

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Install git
          command: |
            apk add git

      - run:
          name: Quay.io login
          command: |
            echo $QUAY_TOKEN | docker login -u=$QUAY_USER --password-stdin quay.io

      - run:
          name: Build 0.6.0-drupal89 image
          command: |
            git checkout 0.6.0-drupal89
            docker build -t quay.io/deviantintegral/drupal_tests:0.6.0-drupal89 . && \
            docker push quay.io/deviantintegral/drupal_tests:0.6.0-drupal89

workflows:
  version: 2
  test_both_versions:
    jobs:
      # This tests both ./setup.sh and ./setup.sh <branch>
      - build
      - build_with_branch
#  update_images:
#    triggers:
#      - schedule:
#          cron: "0 1 * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - build_and_push
